apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-service
  namespace: ai-platform
spec:
  replicas: 2

  selector:
    matchLabels:
      app: embedding-service

  template:
    metadata:
      labels:
        app: embedding-service

    spec:
      serviceAccountName: embedding-service
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: embedding-service
          image: devsecops-ai-service:0.1.0

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          env:
            - name: PORT
              value: "8000"