apiVersion: v1
kind: Service
metadata:
  name: embedding-service
  namespace: ai-platform
spec:
  type: ClusterIP

  selector:
    app: embedding-service

  ports:
    - name: http
      port: 8000
      targetPort: 8000