apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: embedding-service-ingress
  namespace: ai-platform
spec:
  podSelector:
    matchLabels:
      app: embedding-service

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ai-platform

      ports:
        - protocol: TCP
          port: 8000


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: embedding-service-egress
  namespace: ai-platform
spec:
  podSelector:
    matchLabels:
      app: embedding-service

  policyTypes:
    - Egress

  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ai-platform


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: ai-platform
spec:
  podSelector: {}
  policyTypes:
    - Ingress
